/// PDA seed prefix for attestation accounts
pub const ATTESTATION_SEED: &[u8] = b"attestation";

/// SP1 verification key hash for the provenance guest program.
/// Generated by running: cargo run --bin vkey
/// This must be updated whenever the guest program changes.
pub const SP1_VKEY_HASH: &str =
    "0x009878322602e195e87e92e6771e1b212993077890856ee1b40a169c8d4cff27";
