/// PDA seed prefix for attestation accounts
pub const ATTESTATION_SEED: &[u8] = b"attestation";

/// SP1 verification key hash for the provenance guest program.
/// Generated by running: cargo run --bin vkey
/// This must be updated whenever the guest program changes.
pub const SP1_VKEY_HASH: &str =
    "0x0014beac9f9d3c39486f2537e8e5aa7ec0efbf648b9b5ef7e1b403c1d6dc4a1a";
